[build]
target ="aarch64.json"


[target.aarch64.json]
RUSTFLAGS ="-C link-arg=-T./link64.ld"


#buildroot withdebug information


#cross compilation requirements.......

[target.arm-unknown-linux-gnueabihf]
linker="arm-poky-linux-gnueabi-gcc"
rustflags = [
"-C", "link-arg=-mcpu=cortex-a7 ",
"-C", "link-arg=-mfpu=neon-vfpv4 ",
"-C", "link-arg=-mfloat-abi=hard",
"-C", "link-arg=--sysroot=/home/alpha/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/meta-toolchain/1.0-r7/recipe-sysroot",
]


[unstable]
build-std-features= ["compiler-builtins-mem"]
build-std = ["core","compiler_builtins","alloc"]




