[build]
target ="aarch64.json"
[build.aarch64.json]
RUSTFLAGS ="-C link-arg=-T./link64.ld"


[unstable]
build-std-features= ["compiler-builtins-mem"]
build-std = ["core","compiler_builtins","alloc"]




